#!/bin/bash

areapath=.
port=4000

cd "$(dirname "$0")/.." || exit 1   # go to ~/lostmud, not ~/lostmud/area

rm -f shutdown.txt

while true
do
    index=1000
    while true
    do
        logfile=log/$index.log
        [ ! -e "$logfile" ] && break
        index=$((index+1))
    done

    rm -f ./rot
    cp src/rot .
    ./rot $port >& "$logfile"

    if [ -e shutdown.txt ]; then
        rm -f shutdown.txt
        exit 0
    fi

    sleep 15
done
