#!/bin/bash

areapath=.
port=4000
cd $areapath

rm -f shutdown.txt

while true
do
    index=1000
    while true
    do
        logfile=../log/$index.log
        [ ! -e "$logfile" ] && break
        index=$((index+1))
    done

    rm -f ./rot
    cp ../bin/rot .
    ./rot $port >& "$logfile"

    if [ -e shutdown.txt ]; then
        rm -f shutdown.txt
        exit 0
    fi

    sleep 15
done
